;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;   Set miscellaneous emacs prefs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(adoc-enable-two-line-title nil)
 '(adoc-insert-replacement nil)
 '(adoc-unichar-name-resolver nil)
 '(align-open-comment-modes (quote (vhdl-mode emacs-lisp-mode lisp-interaction-mode lisp-mode scheme-mode c++-mode c-mode java-mode perl-mode cperl-mode python-mode makefile-mode ruby-mode)))
 '(align-perl-modes (quote (perl-mode cperl-mode ruby-mode)))
 '(align-text-modes (quote (text-mode outline-mode markdown-mode)))
 '(align-to-tab-stop nil)
 '(c-basic-offset 2)
 '(case-fold-search t)
 '(coffee-tab-width 2)
 '(comment-empty-lines (quote (quote eol)))
 '(comment-multi-line nil)
 '(comment-style (quote indent))
 '(compile-command "cd . ; make -j4 -k")
 '(completion-ignore-case t t)
 '(cperl-break-one-line-blocks-when-indent nil)
 '(cperl-continued-statement-offset 4)
 '(cperl-indent-comment-at-column-0 t)
 '(cperl-indent-left-aligned-comments t)
 '(cperl-indent-level 2)
 '(cperl-indent-parens-as-block t)
 '(cperl-invalid-face nil)
 '(cperl-tab-always-indent nil)
 '(css-indent-offset 2)
 '(current-language-environment "UTF-8")
 '(custom-buffer-style (quote brackets))
 '(custom-magic-show-button t)
 '(default-major-mode (quote text-mode) t)
 '(default-truncate-lines t t)
 '(develock-max-column-plist (quote (emacs-lisp-mode nil lisp-interaction-mode nil change-log-mode nil texinfo-mode nil c-mode nil c++-mode nil java-mode nil jde-mode nil html-mode nil html-helper-mode nil cperl-mode nil perl-mode nil mail-mode nil message-mode nil cmail-mail-mode nil tcl-mode nil ruby-mode nil)))
 '(even-window-heights nil)
 '(fill-column 80)
 '(flymake-allowed-file-name-masks (quote (("^[^#@]+Rakefile$" flymake-ruby-init) ("^[^#@]+\\.rb$" flymake-ruby-init) ("\\.\\(?:c\\(?:pp\\|xx\\|\\+\\+\\)?\\|CC\\)\\'" flymake-simple-make-init) ("\\.xml\\'" flymake-xml-init) ("\\.html?\\'" flymake-xml-init) ("\\.cs\\'" flymake-simple-make-init) ("\\.p[ml]\\'" flymake-perl-init) ("\\.php[345]?\\'" flymake-php-init) ("\\.h\\'" flymake-master-make-header-init flymake-master-cleanup) ("\\.java\\'" flymake-simple-make-java-init flymake-simple-java-cleanup) ("[0-9]+\\.tex\\'" flymake-master-tex-init flymake-master-cleanup) ("\\.tex\\'" flymake-simple-tex-init) ("\\.idl\\'" flymake-simple-make-init))))
 '(flymake-gui-warnings-enabled nil)
 '(flymake-no-changes-timeout 2)
 '(flymake-start-syntax-check-on-find-file nil)
 '(frame-title-format "[%b] in %F, %f" t)
 '(graphviz-dot-indent-width 2)
 '(graphviz-dot-view-command "doted %s")
 '(graphviz-dot-view-edit-command t)
 '(hl-line-mode nil t)
 '(ibuffer-expert t)
 '(icon-title-format "%b" t)
 '(ido-auto-merge-work-directories-length -1)
 '(ido-case-fold t)
 '(ido-default-buffer-method (quote selected-window))
 '(ido-default-file-method (quote selected-window))
 '(ido-enable-flex-matching t)
 '(ido-enable-regexp nil)
 '(ido-ignore-directories (quote ("\\`CVS/" "\\`\\.\\./" "\\`\\./" "\\`\\.svn")))
 '(ido-ignore-files (quote ("\\`CVS/" "\\`#" "\\`.#" "\\`\\.\\./" "\\`\\./" "\\`\\.DS_Store" "\\`\\.Icon" "\\`LICENSE\\'" "\\.bak\\'")))
 '(ido-use-filename-at-point nil)
 '(indent-region-mode nil t)
 '(inhibit-startup-screen t)
 '(javascript-indent-level 2)
 '(jit-lock-chunk-size 5000)
 '(jit-lock-context-time 0.5)
 '(jit-lock-contextually nil)
 '(jit-lock-stealth-load 90)
 '(jit-lock-stealth-time 16)
 '(jit-lock-stealth-verbose t)
 '(js-auto-indent-flag nil)
 '(js2-allow-rhino-new-expr-initializer nil)
 '(js2-cleanup-whitespace t)
 '(js2-concat-multiline-strings nil)
 '(js2-dynamic-idle-timer-adjust 2)
 '(js2-global-externs (quote (module require exports)))
 '(js2-highlight-level 3)
 '(js2-idle-timer-delay 1)
 '(js2-include-browser-externs nil)
 '(js2-include-gears-externs nil)
 '(js2-include-rhino-externs nil)
 '(js2-mirror-mode t)
 '(js2-mode-escape-quotes nil)
 '(js2-mode-indent-ignore-first-tab t)
 '(js2-mode-indent-inhibit-undo t)
 '(js2-mode-show-parse-errors nil)
 '(js2-mode-show-strict-warnings t)
 '(js2-pretty-multiline-decl-indentation-p nil)
 '(js2-rebind-eol-bol-keys nil)
 '(mark-even-if-inactive t)
 '(markdown-footnote-location (quote immediately))
 '(markdown-hr-string "__________________________________________________________________________")
 '(ns-alternate-modifier (quote super))
 '(paren-sexp-mode t)
 '(pig-mode-hook (lambda nil (make-local-variable (quote tab-width)) (set (quote tab-width) 2)))
 '(predictive-mode t)
 '(read-file-name-completion-ignore-case t)
 '(recentf-exclude (quote ("/[^/]+@[^/]+:.*")))
 '(recentf-save-file "~/.recentf")
 '(remote-shell-program "/usr/bin/ssh")
 '(require-final-newline t)
 '(ruby-deep-indent-paren nil)
 '(safe-local-variable-values (quote ((sh-indent-comment . t) (encoding . utf-8) (encoding . binary) (ruby-compilation-executable . "ruby") (ruby-compilation-executable . "ruby1.8") (ruby-compilation-executable . "ruby1.9") (ruby-compilation-executable . "rbx") (ruby-compilation-executable . "jruby") (whitespace-line-column . 80) (lexical-binding . t))))
 '(scroll-bar-mode (quote right))
 '(sh-basic-offset 2)
 '(sh-indentation 2)
 '(show-paren-mode t)
 '(show-paren-style (quote expression))
 '(standard-indent 2)
 '(tab-always-indent nil)
 '(text-mode-hook (quote ((lambda nil (set (make-local-variable (quote indent-tabs-mode)) t)) text-mode-hook-identify)))
 '(tool-bar-mode nil)
 '(tramp-completion-reread-directory-timeout 300)
 '(tramp-default-method "ssh")
 '(transient-mark-mode t)
 '(vc-follow-symlinks t)
 '(visible-bell t)
 '(x-select-enable-clipboard t)
 '(yaml-indent-offset 2))
 

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(fixed-pitch ((t (:family "Menlo"))))
 '(js2-error-face ((t (:foreground "#dc322f" :weight bold))))
 '(js2-external-variable-face ((t (:foreground "#268bd2"))))
 '(js2-function-param-face ((t (:foreground "#016731"))))
 '(js2-instance-member-face ((t (:foreground "DarkOrchid"))))
 '(js2-magic-paren-face ((t nil)))
 '(js2-private-function-call-face ((t (:foreground "#586e75"))))
 '(js2-private-member-face ((t (:foreground "#839496"))))
 '(js2-warning-face ((t (:foreground "black" :underline "orange"))))
 '(markdown-bold-face ((t (:weight bold))))
 '(markdown-header-face ((t (:weight bold :family "Trebuchet MS"))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 1.8))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face :underline t :height 1.5))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face :foreground "#03462c" :slant italic :height 1.325))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face :foreground "dark slate gray" :height 1.25))))
 '(markdown-header-face-5 ((t (:inherit markdown-header-face :height 1.125))))
 '(markdown-header-face-6 ((t (:inherit markdown-header-face :height 1.125))))
 '(markdown-inline-code-face ((t (:inherit font-lock-constant-face))))
 '(markdown-pre-face ((t (:inherit markdown-inline-code-face))))
 '(markup-anchor-face ((t (:inherit markup-meta-face :overline t))))
 '(markup-attribute-face ((t (:inherit markup-meta-face :slant italic))))
 '(markup-command-face ((t (:inherit markup-meta-face :foreground "#93a1a1" :weight bold))))
 '(markup-complex-replacement-face ((t (:inherit markup-meta-face :foreground "#d3ceb9" :box (:line-width 1 :color "#fae9d4")))))
 '(markup-gen-face ((t (:foreground "#305767"))))
 '(markup-internal-reference-face ((t (:inherit markup-meta-face :foreground "#d3ceb9" :underline t))))
 '(markup-list-face ((t (:inherit markup-meta-face :foreground "#555aba" :weight bold))))
 '(markup-meta-face ((t (:stipple nil :foreground "#657b83" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 0.9 :width normal :foundry "unknown" :family "Menlo"))))
 '(markup-meta-hide-face ((t (:inherit markup-meta-face :foreground "#839496" :height 0.9))))
 '(markup-passthrough-face ((t (:inherit (fixed-pitch markup-gen-face) :overline "#cccccc"))))
 '(markup-reference-face ((t (:inherit markup-gen-face :foreground "red" :underline t))))
 '(markup-replacement-face ((t (:inherit (markup-meta-face markup-meta-hide-face) :foreground "#839496" :height 1.25))))
 '(markup-secondary-text-face ((t (:inherit markup-gen-face :foreground "#021d25"))))
 '(markup-title-0-face ((t (:inherit (markup-gen-face markup-title-5-face) :slant normal :height 1.8))))
 '(markup-title-1-face ((t (:inherit (markup-gen-face markup-title-5-face) :underline t :slant normal :height 1.5))))
 '(markup-title-2-face ((t (:inherit (markup-gen-face markup-title-5-face) :foreground "#266294" :underline "#7090b0" :slant normal :height 1.325))))
 '(markup-title-3-face ((t (:inherit (markup-gen-face markup-title-5-face) :slant italic :height 1.25))))
 '(markup-title-4-face ((t (:inherit (markup-gen-face markup-title-5-face) :foreground "#9370db" :slant italic :height 1.125))))
 '(markup-title-5-face ((t (:inherit markup-gen-face :foreground "#206040" :underline nil :slant normal :weight bold :height 1.1 :family "Trebuchet MS"))))
 '(markup-value-face ((t (:inherit markup-meta-face))))
 '(markup-verbatim-face ((t (:background "#faeedc"))))
 '(variable-pitch ((t (:height 1.1 :family "Lucida Grande")))))
