;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;   Set miscellaneous emacs prefs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(align-open-comment-modes (quote (vhdl-mode emacs-lisp-mode lisp-interaction-mode lisp-mode scheme-mode c++-mode c-mode java-mode perl-mode cperl-mode python-mode makefile-mode ruby-mode)))
 '(align-perl-modes (quote (perl-mode cperl-mode ruby-mode)))
 '(auto-save-list-file-prefix "~/.emacs.cruft/auto-saves/.saves-")
 '(backup-directory-alist (list (cons "." (expand-file-name "~/.emacs.cruft/backups/"))))
 '(c-basic-offset 2)
 '(case-fold-search t)
 '(comment-empty-lines (quote (quote eol)))
 '(comment-multi-line nil)
 '(comment-style (quote indent))
 '(compile-command "cd . ; make -j4 -k")
 '(completion-ignore-case t t)
 '(cperl-break-one-line-blocks-when-indent nil)
 '(cperl-continued-statement-offset 4)
 '(cperl-indent-comment-at-column-0 t)
 '(cperl-indent-left-aligned-comments t)
 '(cperl-indent-level 2)
 '(cperl-indent-parens-as-block t)
 '(cperl-invalid-face nil)
 '(cperl-tab-always-indent nil)
 '(css-indent-offset 2)
 '(current-language-environment "UTF-8")
 '(default-major-mode (quote text-mode) t)
 '(default-truncate-lines t t)
 '(develock-max-column-plist (quote (emacs-lisp-mode nil lisp-interaction-mode nil change-log-mode nil texinfo-mode nil c-mode nil c++-mode nil java-mode nil jde-mode nil html-mode nil html-helper-mode nil cperl-mode nil perl-mode nil mail-mode nil message-mode nil cmail-mail-mode nil tcl-mode nil ruby-mode nil)))
 '(even-window-heights nil)
 '(fill-column 80)
 '(flymake-gui-warnings-enabled nil)
 '(frame-title-format "[%b] in %F, %f" t)
 '(hl-line-mode nil t)
 '(ibuffer-expert t)
 '(icon-title-format "%b" t)
 '(ido-auto-merge-work-directories-length -1)
 '(ido-default-buffer-method (quote selected-window))
 '(ido-default-file-method (quote selected-window))
 '(ido-enable-flex-matching t)
 '(ido-enable-regexp nil)
 '(ido-ignore-directories (quote ("\\`CVS/" "\\`\\.\\./" "\\`\\./" "\\`\\.svn")))
 '(ido-ignore-files (quote ("\\`CVS/" "\\`#" "\\`.#" "\\`\\.\\./" "\\`\\./" "\\`\\.DS_Store" "\\`\\.Icon" "\\`LICENSE\\'")))
 '(ido-use-filename-at-point nil)
 '(indent-region-mode nil t)
 '(inhibit-startup-screen t)
 '(javascript-indent-level 2)
 '(js2-dynamic-idle-timer-adjust 2)
 '(js2-idle-timer-delay 1)
 '(mark-even-if-inactive t)
 '(ns-alternate-modifier (quote super))
 '(paren-sexp-mode t)
 '(predictive-mode t)
 '(read-file-name-completion-ignore-case t)
 '(recentf-exclude (quote ("/[^/]+@[^/]+:.*")))
 '(recentf-save-file "~/.emacs.cruft/recentf")
 '(remote-shell-program "/usr/bin/ssh")
 '(require-final-newline t)
 '(ruby-deep-indent-paren nil)
 '(scroll-bar-mode (quote right))
 '(sh-basic-offset 2)
 '(sh-indentation 2)
 '(show-paren-mode t)
 '(show-paren-style (quote expression))
 '(standard-indent 2)
 '(tab-always-indent nil)
 '(tool-bar-mode nil)
 '(tramp-auto-save-directory "~/.emacs.cruft/auto-saves/")
 '(tramp-backup-directory-alist (quote ((".*" . "~/.emacs.cruft/backups/"))))
 '(tramp-completion-reread-directory-timeout 300)
 '(tramp-default-method "ssh")
 '(transient-mark-mode t)
 '(visible-bell t)
 '(x-select-enable-clipboard t t)
 '(yaml-indent-offset 2))
 

(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(rng-error-face ((t (:underline "#eecccc"))))
 '(textile-h1-face ((t (:underline t :weight bold :height 2.0))))
 '(textile-h2-face ((t (:weight bold :height 1.5))))
 '(textile-h3-face ((t (:family "Trebuchet MS" :height 1.325 :slant italic))))
 '(textile-h4-face ((t (:family "Trebuchet MS" :height 1.25 :weight semi-bold :foreground "#002b36" :stipple nil))))
 '(textile-h5-face ((t (:family "Trebuchet MS" :height 1.2 :weight bold :foreground "#002b36")))))
